### ISSUE TITLE
Render script throws Error: invalid template

### ISSUE THREAD

**Issue by jaschaio** [WebReflection/uhtml-ssr#1]
Trying to render a `<script>` tag using `uhtml-ssr`.

Example:

```js
import { render, html } from 'uhtml-ssr';

const config = {
    tracking: {
        facebook: '12345',
        analytics: '12345',
        adwords: '12345',
    },
};

const facebookPixel = `
    <script>
        !function(f,b,e,v,n,t,s)
        {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};
        if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
        n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];
        s.parentNode.insertBefore(t,s)}(window, document,'script',
        'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '${ config.tracking.facebook }');
        fbq('track', 'PageView');
    </script>
    <noscript><img height="1" width="1" style="display:none" src=${ `https://www.facebook.com/tr?id=${ config.tracking.facebook }&ev=PageView&noscript=1` } /></noscript>
`;

const googleTagManager = `
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-60565245-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', '${ config.tracking.analytics }');
        gtag('config', '${ config.tracking.adwords }');
    </script>
`;

const disableGoogleAnalytics = `
    <script type="text/javascript">
        var gaProperty = '${ config.tracking.analytics }';
        var disableStr = 'ga-disable-' + gaProperty;
        
        if ( document.cookie.indexOf( disableStr + '=true' ) > -1 )
            window[disableStr] = true;
    </script>
`;

const content = render( String, html`
    ${ html( facebookPixel ) }
    ${ html( googleTagManager ) }
    ${ html( disableGoogleAnalytics ) }
` );
```

Throws:

```
Error: invalid template
    <script>
        !function(f,b,e,v,n,t,s)
        {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};
        if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
        n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];
        s.parentNode.insertBefore(t,s)}(window, document,'script',
        'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '12345');
        fbq('track', 'PageView');
    </script>
    <noscript><img height="1" width="1" style="display:none" src=https://www.facebook.com/tr?id=12345&ev=PageView&noscript=1 /></noscript>

    at parse (file:///Volumes/Code/app/node_modules/uhtml-ssr/esm/utils.js:132:11)
    at fn (file:///Volumes/Code/app/node_modules/uhtml-ssr/esm/index.js:10:41)
```

Tried the same using `uhtml` and instead get `Uncaught TypeError: Invalid value used as weak map key`: https://codepen.io/jaschaio/pen/jOymeLY?editors=0010

Taking a look at the uhtml issues it seems that using `<script>` tags in templates won't work. But not even on the server side?

**Comment by WebReflection** [comment]
You can't inject strings but you can fake a template so that this works but it doesn't optimize the parsing (repeated each time if the template array is always different).

```js
const content = render( String, html`
    ${ html( [facebookPixel] ) }
    ${ html( [googleTagManager] ) }
    ${ html( [disableGoogleAnalytics] ) }
`);
```

Bear in mind, template literal tag functions accept an *array* as first argument, and zero, one, or more, interpolation values ... if you pass a string, you're failing the template literal function tag syntax, nothing this library will, or should, fix.

```js
const thisIsATag = (template, ...interpolations) => {
  console.log(template); // array
  console.log(interpolations); // ... holes in the template
};

thisIsATag`OK ${'now'}  I get it`;
```
